name: disaster_forecast
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
 
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.0
  google_maps_flutter: ^2.14.0
  http: ^1.5.0
  intl: ^0.19.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_plugin_android_lifecycle: ^2.0.31

flutter:
  uses-material-design: true
  assets:
    - assets/home.png
    - assets/signup_illustration.png
    - assets/login_illustration1.jpg
    - assets/dashboard_banner.png
    - assets/weather_banner1.png